//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentsCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AgentDetails
    {
        public int IDAgent { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Priority { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> Скидка { get; set; }
    }
}
